name: CommandManager
version: 1.2
api: [3.8.2, 3.8.3, 3.9.0]
main: Eren5960\CommandManager\CommandManager
website: github.com/eren5960
author: Eren5960
description: a Command Manager

#perms auto init by CommandManager->onEnable()